facebook:
  facebook_app_id: '492699170774843'
  facebook_secret: '0891c5d2dda959f4334cd82d5804636f'

twitter:
  consumer_key: 'TRqZpzxSq2HgGElvmx046Q'
  consumer_secret: '2ChK1ma7o98TO2LAsnwulZUH9mEQNZwmEAEZirlxQI'

linkedin:

vkontakte:
